"""
agents/youtube_upload.py — YouTube Shorts upload

Handles uploading clips to YouTube Shorts with:
- OAuth2 using refresh token (no manual auth needed after setup)
- Automatic playlist creation/lookup
- Proper Shorts format (#Shorts in description)

Usage:
    from agents.youtube_upload import upload_to_youtube
    video_id = upload_to_youtube(clip_path, title, description, hashtags)
"""
import logging
import os
from pathlib import Path

log = logging.getLogger("youtube")

YOUTUBE_CLIENT_ID = os.getenv("YOUTUBE_CLIENT_ID", "")
YOUTUBE_CLIENT_SECRET = os.getenv("YOUTUBE_CLIENT_SECRET", "")
YOUTUBE_REFRESH_TOKEN = os.getenv("YOUTUBE_REFRESH_TOKEN", "")
PLAYLIST_NAME = "Kick Clips"


def get_youtube_client():
    """Build an authenticated YouTube API client using the refresh token."""
    from google.oauth2.credentials import Credentials
    from googleapiclient.discovery import build

    creds = Credentials(
        token=None,
        refresh_token=YOUTUBE_REFRESH_TOKEN,
        client_id=YOUTUBE_CLIENT_ID,
        client_secret=YOUTUBE_CLIENT_SECRET,
        token_uri="https://oauth2.googleapis.com/token",
    )
    return build("youtube", "v3", credentials=creds)


def get_or_create_playlist(youtube, playlist_name: str) -> str:
    """
    Find an existing playlist by name or create it.
    Returns the playlist ID.
    """
    # Search existing playlists
    response = youtube.playlists().list(
        part="snippet",
        mine=True,
        maxResults=50
    ).execute()

    for item in response.get("items", []):
        if item["snippet"]["title"] == playlist_name:
            playlist_id = item["id"]
            log.info(f"Found playlist '{playlist_name}': {playlist_id}")
            return playlist_id

    # Create new playlist
    log.info(f"Creating playlist '{playlist_name}'...")
    response = youtube.playlists().insert(
        part="snippet,status",
        body={
            "snippet": {
                "title": playlist_name,
                "description": "Clips from Kick streamers, auto-generated by ClipBot",
            },
            "status": {
                "privacyStatus": "public"
            }
        }
    ).execute()

    playlist_id = response["id"]
    log.info(f"Created playlist '{playlist_name}': {playlist_id}")
    return playlist_id


def add_to_playlist(youtube, video_id: str, playlist_id: str):
    """Add a video to a playlist."""
    youtube.playlistItems().insert(
        part="snippet",
        body={
            "snippet": {
                "playlistId": playlist_id,
                "resourceId": {
                    "kind": "youtube#video",
                    "videoId": video_id,
                }
            }
        }
    ).execute()
    log.info(f"Added video {video_id} to playlist {playlist_id}")


def upload_to_youtube(
    clip_path: Path,
    title: str,
    description: str = "",
    hashtags: list[str] = None,
) -> str | None:
    """
    Upload a clip to YouTube Shorts.

    Returns the YouTube video ID on success, None on failure.
    """
    if not all([YOUTUBE_CLIENT_ID, YOUTUBE_CLIENT_SECRET, YOUTUBE_REFRESH_TOKEN]):
        log.warning("YouTube credentials not configured — skipping upload")
        return None

    try:
        from googleapiclient.http import MediaFileUpload

        youtube = get_youtube_client()

        # Build description with hashtags
        hashtag_str = " ".join(hashtags) if hashtags else ""
        full_description = (
            f"{description}\n\n"
            f"{hashtag_str}\n\n"
            f"#Shorts #Kick #Gaming"
        ).strip()

        log.info(f"Uploading to YouTube: {title}")

        # Upload the video
        request = youtube.videos().insert(
            part="snippet,status",
            body={
                "snippet": {
                    "title": title,
                    "description": full_description,
                    "tags": [t.lstrip("#") for t in (hashtags or [])] + ["Shorts", "Kick", "Gaming"],
                    "categoryId": "20",  # Gaming category
                },
                "status": {
                    "privacyStatus": "public",
                    "selfDeclaredMadeForKids": False,
                }
            },
            media_body=MediaFileUpload(
                str(clip_path),
                mimetype="video/mp4",
                resumable=True,
                chunksize=1024 * 1024  # 1MB chunks
            )
        )

        # Execute resumable upload
        response = None
        while response is None:
            status, response = request.next_chunk()
            if status:
                progress = int(status.progress() * 100)
                log.info(f"Upload progress: {progress}%")

        video_id = response["id"]
        log.info(f"Uploaded successfully: https://youtube.com/shorts/{video_id}")

        # Add to playlist
        playlist_id = get_or_create_playlist(youtube, PLAYLIST_NAME)
        add_to_playlist(youtube, video_id, playlist_id)

        return video_id

    except Exception as e:
        log.error(f"YouTube upload failed: {e}")
        return None
